### ISSUE TITLE
Auto task list creation. 

### ISSUE THREAD

**Issue by bokigto** [Uvedale/pfstandardprojectchildren#1]
First of all, this is a great plugin. saves me so much time. 
how would you modify this plugin to add a task list automatically in addition to everything else?

**Comment by Uvedale** [comment]
I'm glad you have found it useful.
I suspect adding a Tasklist would just be a matter of extending the input
json structure to accommodate task lists and then creating and saving
instances of JModelLegacy::getInstance('Tasklist', 'PFtasksModel',
array('ignore_request' => true)) much like it is done in the plugin code
for tasks. I'll see if I can add this next weekend.

Dale

**Comment by bokigto** [comment]
Much appreciated.
